// Generated by CoffeeScript 1.4.0
(function() {
  var assert, engine, filename, fs, o, result, template;

  fs = require('fs');

  assert = require('chai').assert;

  engine = require('../js/coffee-espresso-two-shots.js').getCoffeeEspressoTwoShots();

  o = {};

  filename = process.argv[2];

  o.debug = false;

  if (process.argv[3] != null) {
    switch (process.argv[3]) {
      case '--haml':
        o.format = 'haml';
        break;
      case '--sass':
        o.format = 'sass';
        break;
      case '--debug':
        o.debug = true;
    }
  }

  if (process.argv[4] != null) {
    switch (process.argv[4]) {
      case '--haml':
        o.format = 'haml';
        break;
      case '--sass':
        o.format = 'sass';
        break;
      case '--debug':
        o.debug = true;
    }
  }

  template = fs.readFileSync(filename, 'utf8');

  result = engine.render(template, o);

  fs.writeFile(filename + ".gen", result, function(err) {
    if (err) {
      return console.log(err);
    } else {
      return console.log("==> " + filename + ".gen generated");
    }
  });

}).call(this);
