// Generated by CoffeeScript 1.4.0
(function() {
  var CoffeeEspressoTwoShots, assert, engine, filename, fs, result, template;

  fs = require('fs');

  assert = require('chai').assert;

  CoffeeEspressoTwoShots = require('../js/coffee-espresso-two-shots.js');

  engine = new CoffeeEspressoTwoShots;

  filename = process.argv[2];

  template = fs.readFileSync(filename, 'utf8');

  result = engine.render(template);

  fs.writeFile(filename + ".gen", result, function(err) {
    if (err) {
      return console.log(err);
    } else {
      return console.log("==> " + filename + ".gen generated");
    }
  });

}).call(this);
