// Generated by CoffeeScript 1.4.0
(function() {
  var assert, engine, filename, fs, o, result, template;

  fs = require('fs');

  assert = require('chai').assert;

  engine = require('../js/coffee-espresso-two-shots.js').getCoffeeEspressoTwoShots();

  o = {};

  filename = process.argv[2];

  if ((process.argv[3] != null) && process.argv[3] === '--debug') {
    o.debug = true;
  }

  template = fs.readFileSync(filename, 'utf8');

  result = engine.render(template, o);

  fs.writeFile(filename + ".gen", result, function(err) {
    if (err) {
      return console.log(err);
    } else {
      return console.log("==> " + filename + ".gen generated");
    }
  });

}).call(this);
