// Generated by CoffeeScript 1.4.0
(function() {
  var CoffeeEspressoTwoShots, assert, engine, fs, output, template;

  fs = require('fs');

  assert = require('chai').assert;

  CoffeeEspressoTwoShots = require('../js/coffee-espresso-two-shots.js');

  engine = output = template = null;

  describe('Coffee Espresso Two Shots', function() {
    beforeEach(function() {
      template = output = "";
      return engine = new CoffeeEspressoTwoShots;
    });
    return describe('SaSS test', function() {
      afterEach(function() {
        var result;
        result = engine.render(template);
        return assert.equal(result, output, 'ok');
      });
      it('can convert simple sass code, without mixins', function() {
        template = "body\n  border: 1px solid\n  font-family: 'WhitneyMedium', georgia, sans-serif\n  font-size: 100%\n  #wrapper\n    background-color: #F00\n\n    .container\n      table\n        th:first, td\n          border-bottom: 1px solid #F00";
        return output = "s 'body', ->\n  border '1px solid'\n  font_family '\"WhitneyMedium\", georgia, sans-serif'\n  font_size '100%'\n  s '#wrapper', ->\n    background_color '#F00'\n    s '.container', ->\n      s 'table', ->\n        s 'th:first, td', ->\n          border_bottom '1px solid #F00'\n";
      });
      it('can convert mixin', function() {
        template = "body.users_dashboard #stage.module-08\n  .slide\n    +sprite-bg($general, 'bg-blank-slide')\n    height: 400px";
        return output = "s 'body.users_dashboard #stage.module-08', ->\n  s '.slide', ->\n    sprite_bg general, 'bg-blank-slide'\n    height '400px'\n";
      });
      return it('can ignore this types ("/* and //") comments only', function() {
        template = "// comment 2\n/* comment 3";
        return output = "// comment 2\n/* comment 3\n";
      });
    });
  });

}).call(this);
